### ISSUE TITLE
General MVP

### ISSUE THREAD

**Issue by MarcM987** [JessYRaMa/GitFit#1]
# User Story
* MVP- as a user i want to create a unique username(for a unqiue key) to access my profile. This profile should have my personal info such as height, weight, and age(perhaps for bmi). My weight changes should be logged with time tracking.
* front page should have a log in, create account, and bmi calculator for those to use without an account
## Tasks
- [x] front end inputs (weight should have option for kg or lb; height should have cm or in options)
- [x] back end store table profile data
- [x] each user profile should have a separate table for logs and a chart built from those logs using chart.js

**Comment by MarcM987** [comment]
All good man
